### PR TITLE
Template instead.

### PR DESCRIPTION
**Pull request by jordandukart**

### CODE REVIEW

**Comment by DiegoPino** [comment]
@jordandukart , this bad implementation of preprocess you are correctly fixing here, is present in almost every solution pack. Should we or you open a new ticket on this for a broader fix?

**Comment by jordandukart** [comment]
Worth opening a ticket to audit for it, similarly the comments for templates should be in the form of https://www.drupal.org/node/1354#themepreprocess as @adam-vessey points out. Likely should be another ticket to address this issue and the issue of the variables in the tpl files themselves.

**Comment by DiegoPino** [comment]
Hi @jordandukart, can you open those tickets? Or do you prefer i do so?

**Comment by nigelgbanks** [comment]
https://jira.duraspace.org/browse/ISLANDORA-1071

**Pull request merged**
